import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { Navbar } from "@/Components/Navbar";
import { DistrictManager } from "@/Components/DistrictManager";
import { Users } from "@/Components/Users";

export const getStaticProps = async () => {
  const resp = await fetch("http://www.mocky.io/v2/5d73bf3d3300003733081869");

  const data = await resp.json();

  return {
    props: { users: data },
  };
};

export default function Home({ users }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500&family=Golos+Text&family=Roboto&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Navbar />
        <DistrictManager />
        <Users users={users} />
      </main>
    </>
  );
}
